# Generated by Django 3.1.5 on 2021-01-05 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('secteur', models.CharField(choices=[('AERONAUTIQUE', 'Aeronautique'), ('AUTOMOBILE', 'Automobile'), ('DEFENSE', 'Défense'), ('FERROVIAIRE', 'Ferroviaire'), ('PARAPETROLIER', 'Parapétrolier'), ('ENERGIE', 'Energie')], default='AERONAUTIQUE', max_length=50)),
                ('salarie', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Licence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_licence', models.CharField(choices=[('FULL', 'Full'), ('LIGHT', 'Light')], default='FULL', max_length=50)),
                ('date_debut_validite', models.DateTimeField()),
                ('date_fin_validite', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.company')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='licences',
            field=models.ManyToManyField(to='backend.Licence'),
        ),
    ]
